### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by icedmoca** [lucko/LuckPermsWeb#230]
I don't know if im dumb but `npm run build` gives me:

` ERROR  Failed to compile with 1 errors                                                                  2:37:29 AM

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
No ESLint configuration found.
    at PoolWorker.fromErrorObj (/var/www/html/perms/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at Config.getLocalConfigHierarchy (/var/www/html/perms/node_modules/eslint/lib/config.js:268:39)
    at Config.getConfigHierarchy (/var/www/html/perms/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/var/www/html/perms/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/var/www/html/perms/node_modules/eslint/lib/config.js:342:29)
    at processText (/var/www/html/perms/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (/var/www/html/perms/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (/var/www/html/perms/node_modules/eslint-loader/index.js:278:17)
    at transform (/var/www/html/perms/node_modules/eslint-loader/index.js:252:18)
    at /var/www/html/perms/node_modules/loader-fs-cache/index.js:127:18
    at ReadFileContext.callback (/var/www/html/perms/node_modules/loader-fs-cache/index.js:31:14)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.`

Not a big deal but I can always add .eslintrc.js to it after and it will work. The git clone didn't download it? or npm did something?

**Comment by icedmoca** [comment]
Also to add, `Error: Cannot find module 'node-sass'`

Not a big deal, just have to install it. I'm starting to think I needed to install this lol.
Anyways am I allowed to make a install script once the project releases a non beta?

**Comment by Turbotailz** [comment]
node-sass always causes issues with npm installs, it's not directly related to the project unfortunately so not really something I can fix from here I don't think.

**Comment by Turbotailz** [comment]
Can you send details on your system setup? Like OS version, Node/NPM versions, etc.

**Comment by icedmoca** [comment]
System setup: Pterodactyl Panel, Server Website, XF Forums, Wiki Page
Node: v10.20.1
OS: ubuntu-1804-LTS-bionic-v20200430
Not a big problem though, I just had to download a few packages. The build worked.

**Comment by icedmoca** [comment]
Also to add:
When I try to build:

`* ../wiki/_Sidebar.md in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Wiki.vue?vue&type=script&lang=js&
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! luckperms-web@2.0.1 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the luckperms-web@2.0.1 build script.`

**Comment by Turbotailz** [comment]
Ooh yes, you will also need to clone the wiki submodule:

```
git submodule init
git submodule update
```

Then try build again.

Another thing to add to the readme heh...

**Comment by BrainStone** [comment]
Or ``git clone --recursive``

**Comment by icedmoca** [comment]
Resolved. Added a location entry into nginx. Added ESLint config.
